import { and, desc, eq } from "drizzle-orm";
import { getDb, getPrimaryCompanyForUser } from "../db";
import { ciAdapters, companyContext, conversations, employeeMemories, employees, messages, qaDefects, qaEvents, qaTestCases, qaTestPlans, qaTestResults, qaTestRuns, qaToolPolicies, qaVerifications, taskDependencies, tasks } from "../../drizzle/schema";
import { qaEngineerPersona } from "../agents/personas/qaEngineer";
import { testToolRegistry } from "./adapters";

type TestType = "unit" | "integration" | "api" | "ui" | "end_to_end" | "regression" | "smoke" | "performance" | "security_regression";
const testPlanTemplate: Array<{ title: string; testType: TestType; priority: "medium" | "high"; steps: string; expectedResult: string }> = [
  { title: "Unit behavior", testType: "unit", priority: "medium", steps: "Exercise isolated business rules and boundary conditions.", expectedResult: "The component behavior is deterministic and correct." },
  { title: "Happy path", testType: "regression", priority: "high", steps: "Execute the primary supported user flow.", expectedResult: "The requested behavior completes successfully." },
  { title: "Invalid inputs", testType: "api", priority: "high", steps: "Submit missing, malformed, and boundary inputs.", expectedResult: "Inputs are rejected safely with useful feedback." },
  { title: "Authentication and permissions", testType: "security_regression", priority: "high", steps: "Exercise anonymous, authorized, and unauthorized access.", expectedResult: "Access rules are enforced consistently." },
  { title: "Failure and recovery", testType: "integration", priority: "medium", steps: "Simulate downstream and transient failures.", expectedResult: "Failure is handled without data corruption." },
  { title: "Regression surface", testType: "end_to_end", priority: "medium", steps: "Run affected cross-browser or user-facing flow.", expectedResult: "Existing supported behavior remains intact." },
  { title: "UI interaction", testType: "ui", priority: "medium", steps: "Validate visible states, keyboard paths, and responsive behavior.", expectedResult: "The UI remains accessible and consistent." },
  { title: "Smoke readiness", testType: "smoke", priority: "high", steps: "Exercise the minimal release-critical path.", expectedResult: "The release-critical flow is available." },
  { title: "Performance guardrail", testType: "performance", priority: "medium", steps: "Run an approved non-production performance probe.", expectedResult: "The feature remains within the agreed response guardrail." },
];

function emptyDashboard() { return { qa: { name: qaEngineerPersona.name, role: qaEngineerPersona.role, status: "Monitoring", currentSuite: "Awaiting an approved test plan", qualityStatus: "No run recorded", latestVerification: "No verification recorded" }, run: null as null | { id: string; suiteName: string; status: string; total: number; passed: number; failed: number; skipped: number; durationSeconds: number; riskLevel: string }, defects: [] as Array<{ id: string; defectKey: string; title: string; severity: string; status: string; environment: string }>, events: [] as Array<{ id: string; action: string; summary: string; createdAt: number }>, tools: testToolRegistry, ci: [] as Array<{ id: string; name: string; status: string; capabilities: string[] }> }; }
async function requireCompany(userId: number) { const company = await getPrimaryCompanyForUser(userId); if (!company) throw new Error("No company workspace is available for this user"); return company; }

export async function ensureQaEngineer(companyId: number) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = (await db.select().from(employees).where(and(eq(employees.companyId, companyId), eq(employees.key, "qa-automation-engineer"))).limit(1))[0]; if (existing) return existing; const created = await db.insert(employees).values({ companyId, key: "qa-automation-engineer", name: qaEngineerPersona.name, role: qaEngineerPersona.role, status: "monitoring", model: qaEngineerPersona.modelConfig.model, systemPromptKey: qaEngineerPersona.systemPromptKey, temperature: 10, maxTokens: qaEngineerPersona.modelConfig.maxTokens, toolPermissions: [...qaEngineerPersona.modelConfig.toolPermissions] }); const employeeId = Number((created as unknown as { insertId: number }).insertId); await db.insert(qaToolPolicies).values(testToolRegistry.map((tool) => ({ employeeId, toolName: tool.key, toolType: tool.kind, canRead: true, canExecute: !tool.requiresApproval, canWrite: false, requiresApproval: tool.requiresApproval }))); return (await db.select().from(employees).where(eq(employees.id, employeeId)).limit(1))[0]!; }

export async function getQaDashboardForUser(userId?: number) { if (!userId) return emptyDashboard(); const db = await getDb(); if (!db) return emptyDashboard(); const company = await getPrimaryCompanyForUser(userId); if (!company) return emptyDashboard(); const qa = await ensureQaEngineer(company.id); const [runs, defects, events, ci, sharedMemory] = await Promise.all([db.select().from(qaTestRuns).where(eq(qaTestRuns.companyId, company.id)).orderBy(desc(qaTestRuns.createdAt)).limit(1), db.select().from(qaDefects).where(eq(qaDefects.companyId, company.id)).orderBy(desc(qaDefects.updatedAt)).limit(8), db.select().from(qaEvents).where(eq(qaEvents.companyId, company.id)).orderBy(desc(qaEvents.createdAt)).limit(12), db.select().from(ciAdapters).where(eq(ciAdapters.companyId, company.id)), db.select().from(companyContext).where(eq(companyContext.companyId, company.id))]); const run = runs[0]; const verification = (await db.select().from(qaVerifications).where(and(eq(qaVerifications.companyId, company.id), eq(qaVerifications.employeeId, qa.id))).orderBy(desc(qaVerifications.createdAt)).limit(1))[0]; return { qa: { name: qa.name, role: qa.role, status: qa.status, currentSuite: run?.suiteName ?? "Awaiting an approved test plan", qualityStatus: run ? `${run.status} · ${run.riskLevel} risk` : "No run recorded", latestVerification: verification?.summary ?? "No verification recorded" }, run: run ? { id: `RUN-${run.id}`, suiteName: run.suiteName, status: run.status, total: run.total, passed: run.passed, failed: run.failed, skipped: run.skipped, durationSeconds: run.durationSeconds, riskLevel: run.riskLevel } : null, defects: defects.map((defect) => ({ id: `BUG-${defect.id}`, defectKey: defect.defectKey, title: defect.title, severity: defect.severity, status: defect.status, environment: defect.environment })), events: events.map((event) => ({ id: String(event.id), action: event.action, summary: event.summary, createdAt: event.createdAt.getTime() })), tools: testToolRegistry, ci: ci.map((adapter) => ({ id: String(adapter.id), name: adapter.name, status: adapter.status, capabilities: adapter.capabilities })), sharedMemory: sharedMemory.filter((item) => ["testing_standards", "release_workflow", "quality_risks", "critical_user_flows"].includes(item.category)).map((item) => ({ id: String(item.id), title: item.title, value: item.value, category: item.category })) }; }

export async function createQaPlanForUser(userId: number, input: { title: string; featureDescription: string; riskLevel: "low" | "medium" | "high" | "critical"; testTypes: TestType[] }) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const qa = await ensureQaEngineer(company.id); return db.transaction(async (tx) => { const task = await tx.insert(tasks).values({ companyId: company.id, assignedEmployeeId: qa.id, requestedByUserId: userId, title: input.title, description: input.featureDescription, status: "planning", progress: 0 }); const taskId = Number((task as unknown as { insertId: number }).insertId); const plan = await tx.insert(qaTestPlans).values({ companyId: company.id, employeeId: qa.id, taskId, title: input.title, featureDescription: input.featureDescription, status: "designing", riskLevel: input.riskLevel, summary: "Focused plan covering the requested feature and its risk surface." }); const planId = Number((plan as unknown as { insertId: number }).insertId); const cases = testPlanTemplate.filter((item) => input.testTypes.includes(item.testType) || item.testType === "regression").map((item) => ({ planId, ...item, preconditions: "Approved test environment and relevant fixture data are available.", automationStatus: "candidate" as const })); await tx.insert(qaTestCases).values(cases); await tx.insert(qaEvents).values({ companyId: company.id, employeeId: qa.id, testPlanId: planId, taskId, action: "plan_created", summary: `Created QA plan: ${input.title}.` }); return { planId, taskId, testCaseCount: cases.length }; }); }

export async function recordTestRunForUser(userId: number, input: { planId?: number; taskId?: number; toolName: string; suiteName: string; environment: string; total: number; passed: number; failed: number; skipped: number; durationSeconds: number; riskLevel: "low" | "medium" | "high" | "critical"; summary?: string }) { if (input.passed + input.failed + input.skipped > input.total) throw new Error("Test counts cannot exceed the total"); const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const qa = await ensureQaEngineer(company.id); const status = input.failed ? "failed" : "passed"; const created = await db.insert(qaTestRuns).values({ companyId: company.id, employeeId: qa.id, planId: input.planId, taskId: input.taskId, toolName: input.toolName, suiteName: input.suiteName, environment: input.environment, status, total: input.total, passed: input.passed, failed: input.failed, skipped: input.skipped, durationSeconds: input.durationSeconds, riskLevel: input.riskLevel, summary: input.summary, completedAt: new Date() }); const runId = Number((created as unknown as { insertId: number }).insertId); await db.insert(qaEvents).values({ companyId: company.id, employeeId: qa.id, runId, taskId: input.taskId, action: "run_completed", summary: `${input.suiteName}: ${input.passed} passed, ${input.failed} failed, ${input.skipped} skipped.` }); return { runId, status }; }

export async function createQaDefectForUser(userId: number, input: { runId?: number; taskId?: number; title: string; severity: "blocker" | "critical" | "high" | "medium" | "low"; environment: string; stepsToReproduce: string; expectedResult: string; actualResult: string; evidence: string }) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const [qa, alex, conversation] = await Promise.all([ensureQaEngineer(company.id), db.select().from(employees).where(and(eq(employees.companyId, company.id), eq(employees.key, "full-stack-developer"))).limit(1).then((rows) => rows[0]), db.select().from(conversations).where(eq(conversations.companyId, company.id)).limit(1).then((rows) => rows[0])]); if (!alex || !conversation) throw new Error("Developer or shared conversation is unavailable"); return db.transaction(async (tx) => { const created = await tx.insert(qaDefects).values({ companyId: company.id, runId: input.runId, taskId: input.taskId, reportedByEmployeeId: qa.id, suggestedOwnerEmployeeId: alex.id, defectKey: `BUG-${Date.now()}`, title: input.title, severity: input.severity, environment: input.environment, stepsToReproduce: input.stepsToReproduce, expectedResult: input.expectedResult, actualResult: input.actualResult, evidence: input.evidence }); const defectId = Number((created as unknown as { insertId: number }).insertId); const task = await tx.insert(tasks).values({ companyId: company.id, assignedEmployeeId: alex.id, requestedByUserId: userId, title: `Fix QA defect: ${input.title}`, description: input.actualResult, status: "planning", progress: 0 }); const developerTaskId = Number((task as unknown as { insertId: number }).insertId); if (input.taskId) await tx.insert(taskDependencies).values({ parentTaskId: input.taskId, childTaskId: developerTaskId, dependencyType: "handoff" }); await tx.insert(messages).values([{ conversationId: conversation.id, senderType: "employee", senderEmployeeId: qa.id, content: `Alex, I logged ${input.title} as ${input.severity}. Expected: ${input.expectedResult}. Actual: ${input.actualResult}. Evidence: ${input.evidence}`, messageType: "handoff", relatedTaskId: developerTaskId, createdBy: "employee:qa-automation-engineer" }, { conversationId: conversation.id, senderType: "employee", senderEmployeeId: alex.id, content: "I’ll investigate the defect, apply a targeted fix, and return it for regression verification.", messageType: "task_update", relatedTaskId: developerTaskId, createdBy: "employee:full-stack-developer" }]); await tx.insert(qaEvents).values([{ companyId: company.id, employeeId: qa.id, defectId, taskId: developerTaskId, action: "defect_created", summary: `Created ${input.severity} defect: ${input.title}.` }, { companyId: company.id, employeeId: qa.id, defectId, taskId: developerTaskId, action: "developer_notified", summary: `Assigned defect verification path to ${alex.name}.` }]); return { defectId, developerTaskId }; }); }

export async function verifyQaDefectForUser(userId: number, input: { defectId: number; runId?: number; summary: string; status: "verified" | "failed" | "blocked" }) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const qa = await ensureQaEngineer(company.id); const defect = (await db.select().from(qaDefects).where(and(eq(qaDefects.id, input.defectId), eq(qaDefects.companyId, company.id))).limit(1))[0]; if (!defect) throw new Error("Defect was not found in this company workspace"); await db.transaction(async (tx) => { await tx.insert(qaVerifications).values({ companyId: company.id, defectId: defect.id, runId: input.runId, taskId: defect.taskId, employeeId: qa.id, status: input.status, summary: input.summary }); await tx.update(qaDefects).set({ status: input.status === "verified" ? "verified" : input.status === "failed" ? "in_progress" : "ready_for_verification" }).where(eq(qaDefects.id, defect.id)); await tx.insert(qaEvents).values({ companyId: company.id, employeeId: qa.id, defectId: defect.id, taskId: defect.taskId, action: "verification_completed", summary: input.summary }); }); return { status: input.status }; }

export async function storeQaSharedMemoryForUser(userId: number, input: { category: "testing_standards" | "release_workflow" | "quality_risks" | "critical_user_flows"; title: string; value: string }) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const created = await db.insert(companyContext).values({ companyId: company.id, category: input.category, title: input.title, value: input.value, source: "qa-automation-engineer" }); return { contextId: Number((created as unknown as { insertId: number }).insertId) }; }

export async function createQaRegressionCollaborationForUser(userId: number, input: { teammate: "cybersecurity-analyst" | "data-analyst"; title: string; evidence: string; relatedTaskId?: number }) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const [qa, teammate, conversation] = await Promise.all([ensureQaEngineer(company.id), db.select().from(employees).where(and(eq(employees.companyId, company.id), eq(employees.key, input.teammate))).limit(1).then((rows) => rows[0]), db.select().from(conversations).where(eq(conversations.companyId, company.id)).limit(1).then((rows) => rows[0])]); if (!teammate || !conversation) throw new Error("Requested teammate or shared conversation is unavailable"); const suite = input.teammate === "cybersecurity-analyst" ? "Security regression suite" : "Data behavior regression suite"; return db.transaction(async (tx) => { const task = await tx.insert(tasks).values({ companyId: company.id, assignedEmployeeId: qa.id, requestedByUserId: userId, title: `${suite}: ${input.title}`, description: input.evidence, status: "planning", progress: 0 }); const taskId = Number((task as unknown as { insertId: number }).insertId); if (input.relatedTaskId) await tx.insert(taskDependencies).values({ parentTaskId: input.relatedTaskId, childTaskId: taskId, dependencyType: "handoff" }); const verification = await tx.insert(qaVerifications).values({ companyId: company.id, taskId, employeeId: qa.id, status: "pending", summary: `Pending regression verification for ${input.title}.` }); const verificationId = Number((verification as unknown as { insertId: number }).insertId); await tx.insert(messages).values([{ conversationId: conversation.id, senderType: "employee", senderEmployeeId: teammate.id, content: input.teammate === "cybersecurity-analyst" ? `Priya, please add a security regression for ${input.title}. Evidence: ${input.evidence}` : `Priya, please verify the data behavior for ${input.title}. Evidence: ${input.evidence}`, messageType: "handoff", relatedTaskId: taskId, createdBy: `employee:${input.teammate}` }, { conversationId: conversation.id, senderType: "employee", senderEmployeeId: qa.id, content: `I’ll create the focused regression coverage, run it in an approved environment, and report the verification result.`, messageType: "task_update", relatedTaskId: taskId, createdBy: "employee:qa-automation-engineer" }]); await tx.insert(qaEvents).values({ companyId: company.id, employeeId: qa.id, taskId, action: input.teammate === "cybersecurity-analyst" ? "security_regression_created" : "data_regression_created", summary: `Created ${suite.toLowerCase()} for ${input.title}.` }); return { taskId, suite, verificationId }; }); }

export async function getQaMemoryForUser(userId: number) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const company = await requireCompany(userId); const qa = await ensureQaEngineer(company.id); return db.select().from(employeeMemories).where(and(eq(employeeMemories.companyId, company.id), eq(employeeMemories.employeeId, qa.id))); }
